// ─────────────────────────────────────────────
//  DMC Thread Color Data  (~454 colors)
// ─────────────────────────────────────────────
export const DMC_COLORS = [
  // Whites & Ecrus
  {n:'Blanc',   num:'Blanc', hex:'#ffffff', family:'Whites'},
  {n:'Ecru',    num:'Ecru',  hex:'#f0ead6', family:'Whites'},
  {n:'White Almond', num:'3865', hex:'#faf6f0', family:'Whites'},
  // Blacks & Grays
  {n:'Black',         num:'310',  hex:'#030303', family:'Blacks & Grays'},
  {n:'Very Dark Gray',num:'3799', hex:'#3b3b3b', family:'Blacks & Grays'},
  {n:'Dark Gray',     num:'413',  hex:'#555151', family:'Blacks & Grays'},
  {n:'Gray',          num:'414',  hex:'#807c7c', family:'Blacks & Grays'},
  {n:'Medium Gray',   num:'415',  hex:'#c5c5c5', family:'Blacks & Grays'},
  {n:'Light Gray',    num:'762',  hex:'#dcdcdc', family:'Blacks & Grays'},
  {n:'Pewter Gray',   num:'317',  hex:'#6e6a6a', family:'Blacks & Grays'},
  {n:'Steel Gray',    num:'318',  hex:'#aaaaaa', family:'Blacks & Grays'},
  // Reds
  {n:'Dark Red',              num:'498',  hex:'#9e0b0f', family:'Reds'},
  {n:'Medium Christmas Red',  num:'304',  hex:'#b01217', family:'Reds'},
  {n:'Christmas Red',         num:'321',  hex:'#c51920', family:'Reds'},
  {n:'Red',                   num:'666',  hex:'#ed1c24', family:'Reds'},
  {n:'Bright Red',            num:'606',  hex:'#f0141e', family:'Reds'},
  {n:'Very Dark Cranberry',   num:'815',  hex:'#8b1a2a', family:'Reds'},
  {n:'Dark Cranberry',        num:'816',  hex:'#a82030', family:'Reds'},
  {n:'Cranberry',             num:'817',  hex:'#c02840', family:'Reds'},
  {n:'Very Dark Garnet',      num:'902',  hex:'#7c1628', family:'Reds'},
  {n:'Dark Garnet',           num:'814',  hex:'#8e1a2e', family:'Reds'},
  {n:'Garnet',                num:'309',  hex:'#b01e38', family:'Reds'},
  {n:'Light Garnet',          num:'335',  hex:'#e03050', family:'Reds'},
  {n:'Rose',                  num:'326',  hex:'#d03050', family:'Reds'},
  {n:'Very Dark Rose',        num:'777',  hex:'#991830', family:'Reds'},
  {n:'Dark Rose',             num:'326',  hex:'#cc2244', family:'Reds'},
  // Pinks
  {n:'Very Dark Dusty Rose',  num:'3350', hex:'#c0305a', family:'Pinks'},
  {n:'Dark Dusty Rose',       num:'3731', hex:'#d84875', family:'Pinks'},
  {n:'Dusty Rose',            num:'3733', hex:'#e87090', family:'Pinks'},
  {n:'Light Dusty Rose',      num:'3326', hex:'#f4a0b0', family:'Pinks'},
  {n:'Very Light Dusty Rose', num:'819',  hex:'#fad4dc', family:'Pinks'},
  {n:'Dark Carnation',        num:'891',  hex:'#e03060', family:'Pinks'},
  {n:'Carnation',             num:'892',  hex:'#e85878', family:'Pinks'},
  {n:'Light Carnation',       num:'893',  hex:'#f07898', family:'Pinks'},
  {n:'Very Light Carnation',  num:'894',  hex:'#f8a8b8', family:'Pinks'},
  {n:'Ultra Light Carnation', num:'3713', hex:'#fdd0d8', family:'Pinks'},
  {n:'Dark Pink',             num:'961',  hex:'#c84070', family:'Pinks'},
  {n:'Pink',                  num:'962',  hex:'#e06090', family:'Pinks'},
  {n:'Light Pink',            num:'963',  hex:'#f8a0b8', family:'Pinks'},
  {n:'Salmon',                num:'760',  hex:'#f08080', family:'Pinks'},
  {n:'Light Salmon',          num:'761',  hex:'#f8a898', family:'Pinks'},
  {n:'Very Light Salmon',     num:'3713', hex:'#fdd0c8', family:'Pinks'},
  {n:'Hot Pink',              num:'956',  hex:'#f04068', family:'Pinks'},
  {n:'Geranium',              num:'351',  hex:'#e06050', family:'Pinks'},
  {n:'Light Geranium',        num:'352',  hex:'#f08070', family:'Pinks'},
  {n:'Pale Geranium',         num:'353',  hex:'#f8b098', family:'Pinks'},
  {n:'Very Dark Coral',       num:'347',  hex:'#c03030', family:'Pinks'},
  {n:'Dark Coral',            num:'349',  hex:'#d04040', family:'Pinks'},
  {n:'Coral',                 num:'350',  hex:'#e05050', family:'Pinks'},
  // Oranges
  {n:'Very Dark Burnt Orange',num:'900',  hex:'#c03010', family:'Oranges'},
  {n:'Dark Burnt Orange',     num:'946',  hex:'#e04010', family:'Oranges'},
  {n:'Burnt Orange',          num:'947',  hex:'#f05020', family:'Oranges'},
  {n:'Light Burnt Orange',    num:'3340', hex:'#f07040', family:'Oranges'},
  {n:'Very Dark Orange Spice',num:'720',  hex:'#c84010', family:'Oranges'},
  {n:'Dark Orange Spice',     num:'721',  hex:'#dc6020', family:'Oranges'},
  {n:'Orange Spice',          num:'722',  hex:'#e88040', family:'Oranges'},
  {n:'Light Orange Spice',    num:'3341', hex:'#f8a878', family:'Oranges'},
  {n:'Apricot',               num:'3341', hex:'#f8c090', family:'Oranges'},
  {n:'Light Apricot',         num:'3824', hex:'#fdd4b0', family:'Oranges'},
  {n:'Dark Tangerine',        num:'741',  hex:'#f87020', family:'Oranges'},
  {n:'Tangerine',             num:'742',  hex:'#f89030', family:'Oranges'},
  {n:'Light Tangerine',       num:'743',  hex:'#f8b050', family:'Oranges'},
  {n:'Very Light Tangerine',  num:'744',  hex:'#f8cc80', family:'Oranges'},
  // Yellows
  {n:'Dark Topaz',            num:'781',  hex:'#a06010', family:'Yellows'},
  {n:'Topaz',                 num:'782',  hex:'#c07820', family:'Yellows'},
  {n:'Medium Topaz',          num:'783',  hex:'#d89030', family:'Yellows'},
  {n:'Light Topaz',           num:'725',  hex:'#f0b840', family:'Yellows'},
  {n:'Very Light Topaz',      num:'726',  hex:'#f8d060', family:'Yellows'},
  {n:'Pale Yellow',           num:'727',  hex:'#fce880', family:'Yellows'},
  {n:'Dark Yellow',           num:'3820', hex:'#d4a020', family:'Yellows'},
  {n:'Yellow',                num:'3821', hex:'#e8b828', family:'Yellows'},
  {n:'Light Yellow',          num:'3822', hex:'#f4cc60', family:'Yellows'},
  {n:'Very Light Yellow',     num:'3823', hex:'#fffacc', family:'Yellows'},
  {n:'Canary',                num:'972',  hex:'#f8c010', family:'Yellows'},
  {n:'Light Canary',          num:'973',  hex:'#f8d820', family:'Yellows'},
  {n:'Pale Canary',           num:'3078', hex:'#fef8c0', family:'Yellows'},
  {n:'Lemon',                 num:'307',  hex:'#f8e840', family:'Yellows'},
  {n:'Dark Lemon',            num:'444',  hex:'#f0c800', family:'Yellows'},
  {n:'Lemon Yellow',          num:'445',  hex:'#f8f080', family:'Yellows'},
  {n:'Gold',                  num:'676',  hex:'#d4a840', family:'Yellows'},
  {n:'Light Gold',            num:'677',  hex:'#e8c870', family:'Yellows'},
  {n:'Very Dark Old Gold',    num:'680',  hex:'#a07020', family:'Yellows'},
  {n:'Dark Old Gold',         num:'729',  hex:'#b88030', family:'Yellows'},
  {n:'Old Gold',              num:'3829', hex:'#c89038', family:'Yellows'},
  {n:'Light Old Gold',        num:'834',  hex:'#d4a84c', family:'Yellows'},
  // Yellow-Greens
  {n:'Dark Moss Green',       num:'469',  hex:'#607830', family:'Yellow-Greens'},
  {n:'Moss Green',            num:'470',  hex:'#789040', family:'Yellow-Greens'},
  {n:'Light Moss Green',      num:'471',  hex:'#90a858', family:'Yellow-Greens'},
  {n:'Very Light Moss Green', num:'472',  hex:'#b8c880', family:'Yellow-Greens'},
  {n:'Dark Avocado Green',    num:'936',  hex:'#506030', family:'Yellow-Greens'},
  {n:'Avocado Green',         num:'937',  hex:'#688040', family:'Yellow-Greens'},
  {n:'Medium Avocado Green',  num:'3346', hex:'#507840', family:'Yellow-Greens'},
  {n:'Light Avocado Green',   num:'3347', hex:'#789858', family:'Yellow-Greens'},
  {n:'Very Light Avocado',    num:'3348', hex:'#a8c080', family:'Yellow-Greens'},
  {n:'Dark Yellow Green',     num:'733',  hex:'#a09830', family:'Yellow-Greens'},
  {n:'Yellow Green',          num:'734',  hex:'#b8b040', family:'Yellow-Greens'},
  {n:'Light Yellow Green',    num:'3819', hex:'#d8d860', family:'Yellow-Greens'},
  {n:'Chartreuse',            num:'703',  hex:'#70c030', family:'Yellow-Greens'},
  {n:'Light Chartreuse',      num:'704',  hex:'#90d840', family:'Yellow-Greens'},
  // Greens
  {n:'Very Dark Forest Green',num:'986',  hex:'#205830', family:'Greens'},
  {n:'Dark Forest Green',     num:'987',  hex:'#307040', family:'Greens'},
  {n:'Forest Green',          num:'988',  hex:'#508858', family:'Greens'},
  {n:'Light Forest Green',    num:'989',  hex:'#78a870', family:'Greens'},
  {n:'Very Dark Green',       num:'895',  hex:'#104820', family:'Greens'},
  {n:'Dark Christmas Green',  num:'909',  hex:'#186030', family:'Greens'},
  {n:'Christmas Green',       num:'911',  hex:'#287840', family:'Greens'},
  {n:'Medium Christmas Green',num:'912',  hex:'#389050', family:'Greens'},
  {n:'Light Christmas Green', num:'913',  hex:'#58a870', family:'Greens'},
  {n:'Emerald Green',         num:'911',  hex:'#10a040', family:'Greens'},
  {n:'Dark Emerald',          num:'3818', hex:'#085830', family:'Greens'},
  {n:'Very Dark Pistachio',   num:'319',  hex:'#305830', family:'Greens'},
  {n:'Dark Pistachio',        num:'320',  hex:'#487848', family:'Greens'},
  {n:'Pistachio',             num:'368',  hex:'#70a068', family:'Greens'},
  {n:'Light Pistachio',       num:'369',  hex:'#98c890', family:'Greens'},
  {n:'Pale Pistachio',        num:'3348', hex:'#c0e0b0', family:'Greens'},
  {n:'Very Dark Hunter Green',num:'3345', hex:'#285028', family:'Greens'},
  {n:'Dark Hunter Green',     num:'3346', hex:'#386838', family:'Greens'},
  {n:'Hunter Green',          num:'3347', hex:'#588058', family:'Greens'},
  {n:'Light Hunter Green',    num:'3348', hex:'#88a880', family:'Greens'},
  {n:'Sea Green',             num:'3851', hex:'#40a878', family:'Greens'},
  {n:'Bright Green',          num:'700',  hex:'#007830', family:'Greens'},
  {n:'Light Bright Green',    num:'701',  hex:'#108840', family:'Greens'},
  {n:'Medium Bright Green',   num:'702',  hex:'#28a050', family:'Greens'},
  {n:'Jade',                  num:'563',  hex:'#68c090', family:'Greens'},
  {n:'Light Jade',            num:'564',  hex:'#90d0a8', family:'Greens'},
  // Teals & Aquas
  {n:'Very Dark Teal',        num:'3808', hex:'#205060', family:'Teals & Aquas'},
  {n:'Dark Teal',             num:'3809', hex:'#306878', family:'Teals & Aquas'},
  {n:'Teal',                  num:'3810', hex:'#408898', family:'Teals & Aquas'},
  {n:'Light Teal',            num:'3811', hex:'#80b8c8', family:'Teals & Aquas'},
  {n:'Very Light Teal',       num:'928',  hex:'#b8d8e0', family:'Teals & Aquas'},
  {n:'Very Dark Turquoise',   num:'3809', hex:'#1870a0', family:'Teals & Aquas'},
  {n:'Dark Turquoise',        num:'3810', hex:'#2890b8', family:'Teals & Aquas'},
  {n:'Turquoise',             num:'3811', hex:'#40b0d0', family:'Teals & Aquas'},
  {n:'Light Turquoise',       num:'958',  hex:'#50c8c0', family:'Teals & Aquas'},
  {n:'Dark Aquamarine',       num:'959',  hex:'#38b8a8', family:'Teals & Aquas'},
  {n:'Aquamarine',            num:'964',  hex:'#78d0c0', family:'Teals & Aquas'},
  {n:'Light Aquamarine',      num:'966',  hex:'#a8e0d0', family:'Teals & Aquas'},
  {n:'Seafoam Green',         num:'163',  hex:'#48a878', family:'Teals & Aquas'},
  {n:'Light Seafoam',         num:'164',  hex:'#80c8a0', family:'Teals & Aquas'},
  // Blues
  {n:'Very Dark Navy',        num:'336',  hex:'#0c1848', family:'Blues'},
  {n:'Dark Navy',             num:'823',  hex:'#101e58', family:'Blues'},
  {n:'Navy',                  num:'824',  hex:'#183070', family:'Blues'},
  {n:'Dark Royal Blue',       num:'820',  hex:'#1030a0', family:'Blues'},
  {n:'Royal Blue',            num:'825',  hex:'#1848b8', family:'Blues'},
  {n:'Medium Royal Blue',     num:'826',  hex:'#3060c8', family:'Blues'},
  {n:'Light Royal Blue',      num:'827',  hex:'#70a0d8', family:'Blues'},
  {n:'Very Light Royal Blue', num:'3755', hex:'#a0c0e8', family:'Blues'},
  {n:'Very Dark Cornflower',  num:'791',  hex:'#283078', family:'Blues'},
  {n:'Dark Cornflower',       num:'792',  hex:'#384898', family:'Blues'},
  {n:'Cornflower Blue',       num:'793',  hex:'#5870b8', family:'Blues'},
  {n:'Medium Cornflower',     num:'794',  hex:'#8098cc', family:'Blues'},
  {n:'Light Cornflower',      num:'3840', hex:'#a0b8e0', family:'Blues'},
  {n:'Dark Baby Blue',        num:'334',  hex:'#406898', family:'Blues'},
  {n:'Baby Blue',             num:'322',  hex:'#6090b8', family:'Blues'},
  {n:'Light Baby Blue',       num:'3325', hex:'#a0c0d8', family:'Blues'},
  {n:'Pale Baby Blue',        num:'828',  hex:'#c8e0f0', family:'Blues'},
  {n:'Dark Delft Blue',       num:'798',  hex:'#385890', family:'Blues'},
  {n:'Delft Blue',            num:'799',  hex:'#5070a8', family:'Blues'},
  {n:'Medium Delft Blue',     num:'800',  hex:'#7890c0', family:'Blues'},
  {n:'Light Delft Blue',      num:'3839', hex:'#90a8d0', family:'Blues'},
  {n:'Pale Delft',            num:'3840', hex:'#b8ccE4', family:'Blues'},
  {n:'Denim Blue',            num:'311',  hex:'#204060', family:'Blues'},
  {n:'Dark Wedgwood',         num:'3750', hex:'#204878', family:'Blues'},
  {n:'Wedgwood',              num:'518',  hex:'#3870a0', family:'Blues'},
  {n:'Light Wedgwood',        num:'519',  hex:'#6090b8', family:'Blues'},
  {n:'Sky Blue',              num:'519',  hex:'#88b8d0', family:'Blues'},
  {n:'Light Sky Blue',        num:'747',  hex:'#d0ecf8', family:'Blues'},
  {n:'Pale Sky Blue',         num:'3753', hex:'#dce8f4', family:'Blues'},
  // Blue-Violets
  {n:'Very Dark Blue Violet', num:'333',  hex:'#3c2880', family:'Blue-Violets'},
  {n:'Dark Blue Violet',      num:'3746', hex:'#5840a0', family:'Blue-Violets'},
  {n:'Blue Violet',           num:'340',  hex:'#7060b8', family:'Blue-Violets'},
  {n:'Medium Blue Violet',    num:'341',  hex:'#9080cc', family:'Blue-Violets'},
  {n:'Light Blue Violet',     num:'3747', hex:'#b8b0e0', family:'Blue-Violets'},
  {n:'Very Dark Periwinkle',  num:'791',  hex:'#404890', family:'Blue-Violets'},
  {n:'Periwinkle',            num:'3838', hex:'#5868b0', family:'Blue-Violets'},
  {n:'Light Periwinkle',      num:'3839', hex:'#8090c8', family:'Blue-Violets'},
  {n:'Pale Periwinkle',       num:'3840', hex:'#aab0d8', family:'Blue-Violets'},
  // Purples & Violets
  {n:'Very Dark Violet',      num:'550',  hex:'#480868', family:'Purples'},
  {n:'Dark Violet',           num:'552',  hex:'#701090', family:'Purples'},
  {n:'Violet',                num:'553',  hex:'#9030a8', family:'Purples'},
  {n:'Medium Violet',         num:'554',  hex:'#b860c0', family:'Purples'},
  {n:'Light Violet',          num:'3836', hex:'#d090d0', family:'Purples'},
  {n:'Very Dark Purple',      num:'154',  hex:'#3c0850', family:'Purples'},
  {n:'Dark Purple',           num:'155',  hex:'#604880', family:'Purples'},
  {n:'Purple',                num:'156',  hex:'#8070a8', family:'Purples'},
  {n:'Medium Purple',         num:'157',  hex:'#a098c0', family:'Purples'},
  {n:'Light Purple',          num:'3837', hex:'#8038a0', family:'Purples'},
  {n:'Lavender',              num:'209',  hex:'#b878c8', family:'Purples'},
  {n:'Dark Lavender',         num:'208',  hex:'#906090', family:'Purples'},
  {n:'Medium Lavender',       num:'210',  hex:'#cc98d8', family:'Purples'},
  {n:'Light Lavender',        num:'211',  hex:'#e0c0e8', family:'Purples'},
  {n:'Pale Lavender',         num:'3743', hex:'#d0c8d8', family:'Purples'},
  {n:'Very Pale Lavender',    num:'3042', hex:'#c0b0c0', family:'Purples'},
  {n:'Antique Violet',        num:'3041', hex:'#906080', family:'Purples'},
  {n:'Dark Antique Violet',   num:'3740', hex:'#685070', family:'Purples'},
  // Mauves & Plums
  {n:'Very Dark Mauve',       num:'3685', hex:'#800040', family:'Mauves & Plums'},
  {n:'Dark Mauve',            num:'3687', hex:'#a04060', family:'Mauves & Plums'},
  {n:'Mauve',                 num:'3688', hex:'#c07090', family:'Mauves & Plums'},
  {n:'Light Mauve',           num:'3689', hex:'#e0a0b8', family:'Mauves & Plums'},
  {n:'Very Dark Plum',        num:'915',  hex:'#780848', family:'Mauves & Plums'},
  {n:'Dark Plum',             num:'718',  hex:'#981060', family:'Mauves & Plums'},
  {n:'Plum',                  num:'917',  hex:'#b01878', family:'Mauves & Plums'},
  {n:'Medium Plum',           num:'316',  hex:'#c06080', family:'Mauves & Plums'},
  {n:'Light Plum',            num:'3836', hex:'#d898b0', family:'Mauves & Plums'},
  {n:'Dark Dusty Mauve',      num:'3726', hex:'#906070', family:'Mauves & Plums'},
  {n:'Dusty Mauve',           num:'3727', hex:'#c09098', family:'Mauves & Plums'},
  // Browns & Tans
  {n:'Very Dark Brown',       num:'3371', hex:'#1c0e08', family:'Browns & Tans'},
  {n:'Dark Brown',            num:'838',  hex:'#3c2010', family:'Browns & Tans'},
  {n:'Brown',                 num:'839',  hex:'#583018', family:'Browns & Tans'},
  {n:'Medium Brown',          num:'840',  hex:'#7c4820', family:'Browns & Tans'},
  {n:'Light Brown',           num:'841',  hex:'#a86838', family:'Browns & Tans'},
  {n:'Very Light Brown',      num:'842',  hex:'#c89060', family:'Browns & Tans'},
  {n:'Dark Coffee Brown',     num:'801',  hex:'#4a2810', family:'Browns & Tans'},
  {n:'Coffee Brown',          num:'433',  hex:'#6a3818', family:'Browns & Tans'},
  {n:'Medium Coffee Brown',   num:'434',  hex:'#8a5020', family:'Browns & Tans'},
  {n:'Light Coffee Brown',    num:'435',  hex:'#aa6828', family:'Browns & Tans'},
  {n:'Very Light Coffee',     num:'436',  hex:'#c88838', family:'Browns & Tans'},
  {n:'Tan',                   num:'437',  hex:'#d8a860', family:'Browns & Tans'},
  {n:'Dark Mocha Brown',      num:'3031', hex:'#3a2010', family:'Browns & Tans'},
  {n:'Mocha Brown',           num:'3032', hex:'#7a5838', family:'Browns & Tans'},
  {n:'Medium Mocha Brown',    num:'3033', hex:'#a88060', family:'Browns & Tans'},
  {n:'Very Dark Hazelnut',    num:'869',  hex:'#684020', family:'Browns & Tans'},
  {n:'Dark Hazelnut',         num:'420',  hex:'#8a5828', family:'Browns & Tans'},
  {n:'Hazelnut',              num:'422',  hex:'#b08040', family:'Browns & Tans'},
  {n:'Light Hazelnut',        num:'3047', hex:'#d8b87a', family:'Browns & Tans'},
  {n:'Very Light Hazelnut',   num:'3046', hex:'#e8d098', family:'Browns & Tans'},
  {n:'Pale Hazelnut',         num:'3045', hex:'#c8a060', family:'Browns & Tans'},
  {n:'Dark Golden Brown',     num:'975',  hex:'#8a5010', family:'Browns & Tans'},
  {n:'Golden Brown',          num:'976',  hex:'#b07828', family:'Browns & Tans'},
  {n:'Medium Golden Brown',   num:'977',  hex:'#c89040', family:'Browns & Tans'},
  {n:'Light Golden Brown',    num:'3828', hex:'#d0a85a', family:'Browns & Tans'},
  // Beiges & Creams
  {n:'Very Dark Beige Brown', num:'3781', hex:'#706048', family:'Beiges & Creams'},
  {n:'Dark Beige Brown',      num:'3782', hex:'#9a8060', family:'Beiges & Creams'},
  {n:'Beige Brown',           num:'3828', hex:'#b89870', family:'Beiges & Creams'},
  {n:'Light Beige Brown',     num:'3033', hex:'#c8b088', family:'Beiges & Creams'},
  {n:'Pale Beige',            num:'543',  hex:'#e0cca8', family:'Beiges & Creams'},
  {n:'Very Light Beige',      num:'3866', hex:'#f0e8d8', family:'Beiges & Creams'},
  {n:'Linen',                 num:'3865', hex:'#f4ede0', family:'Beiges & Creams'},
  {n:'Antique White',         num:'746',  hex:'#f8f4e8', family:'Beiges & Creams'},
  {n:'Very Light Tan',        num:'738',  hex:'#dfc090', family:'Beiges & Creams'},
  {n:'Light Tan',             num:'739',  hex:'#ead8b0', family:'Beiges & Creams'},
];
